### ISSUE TITLE
Pull request newbie question

### ISSUE THREAD

**Issue by jpietrzak8** [DragonStuff/ChipShippingTimes#1]
Hi DragonStuff,

I haven't done too much collaborative work on GitHub before.  My understanding is that before I can make a pull request on that shipping times file, I would need to have my own branch of your repository?  (Or, at the very least, authorized access to the ChipShippingTimes repository.)  Is there a simpler step I'm missing?  Thanks!

**Comment by DragonStuff** [comment]
Hey there @jpietrzak8. No worries, I have found this guide quite useful: http://kbroman.org/github_tutorial/pages/fork.html

Thanks for your contribution!
